# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 210b0725553a286110949966ade8134e68673dd214d07ec5139781af1f9e0f204d88d1630dd67b872c40dbb1e67721e86c931b718c3c8c757bc7ce65a1817137

test:
  secret_key_base: feb6099ec4ec04cc27fe17f3c813e58407443baa7dba27733fd107643aed504163c5b3bd4384e2c46a1c5867a7d92b3788aa4b6612a1238573fe7e8227ad8224

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
